### ISSUE TITLE
Please add the feature to re-order the list

### ISSUE THREAD

**Issue by kdon80** [RedMarlin/OctoberCMS-Faq#1]
Please add the feature to re-order the list.

thanks

**Comment by RedMarlin** [comment]
Could you specify what list and in which place you want to re-order? Also could you specify what new order you want it to be?

**Comment by kdon80** [comment]
By the list I'm referring to the Questions under a certain category.
For simplicity, let's say there is only one category, and I have 20 questions listed under that one category. I want to be able to change the ordering of the questions. From what I can see, when the page is rendered, the questions are ordered DESC right from the database, so the latest question shows up on top of the page.

**Comment by RedMarlin** [comment]
OK, so you want to choose by hand the questions order. For example by assigning a number to each question, is that correct?

**Comment by kdon80** [comment]
Precisely.
Maybe adding a new 'ordering' column in the DB that would keep track of that. And in the interface, we can drag and drop to reorder the questions?
As far as the design goes, to add the draggability in the 'Questions' tab, I can see it can be a bit tricky since every question from any category is listed in there. 
Maybe you can add a new tab to the two you already have (Questions and Categories) and name it something like "Ordering". in here, a dropdown would allow the user to pick a category. Once a category is selected, it would then lists only the 'title' of the questions under that category. Then the user would be able to drag them to reorder - and the reordered would automatically save after each drag.

Just throwing some ideas around.

Thanks for considering this feature. I really think this feature is needed. Imagine having 10 FAQs in one category in one page. Some of them might be related and should be grouped together, but the admin added them far apart at different times.

**Comment by RedMarlin** [comment]
Indeed this feature can be handy. 
I must check this drag and drop ordering in backend, to see if its doable and how much it will take.
For sure I will add the simplified implementation (additional DB field and input field to sort with number) soon.

**Comment by RedMarlin** [comment]
Do you know any other October plugin that is using drag and drop in backend?

**Comment by kdon80** [comment]
Sorry, I don't know any.
If you can't find one, I have jquery code that I'm using on my application in front end, that does a similar task. I can share that with you.

**Comment by RedMarlin** [comment]
Never mind, found it
http://octobercms.com/docs/backend/reorder
October is incredible :)

**Comment by kdon80** [comment]
Awesome!

**Comment by RedMarlin** [comment]
I have added sorting, could you test it?
For that you should copy files from github repo to faq plugin directory and force update.

**Comment by kdon80** [comment]
Great. I'm going to test it now

**Comment by kdon80** [comment]
Do you know if ForceUpdate will overwrite Frozen plugins? I have several PlugIns that are set to Freeze Update because I did customization on them. I've never done a ForceUpdate before, so I don't know the repercussion. Do you know?

**Comment by RedMarlin** [comment]
I have no idea as normally I dont modify plugins directly. You can just login out and then log in to your admin panel as it should update te FAQ plugin also.

**Comment by kdon80** [comment]
I tried that but didn't update your plugin. I just posted that question on October's forum, hopefully someone will respond.

**Comment by kdoonboli** [comment]
I decided to do the FORCE update you suggested. But I don't see any changes to plugin... where should I go?

**Comment by RedMarlin** [comment]
Did you try to logout and login in? To get to the sorting function you need to enter Category and then edit a category. There you will have a button to sort questions in this category.

**Comment by RedMarlin** [comment]
I have made some small fixes and uploaded the updated version to October marketplace. It soon should be available there so update will be possible straight from october backend.

EDIT: The new version that enables sorting is on the marketplace.

**Comment by kdoonboli** [comment]
Hey bud, there is a bug. You hard-coded 'backend' in the redirect, so it doesn't work for me :)

 public function onLinkSort($recordId = null)
    {
        return Redirect::to('/backend/redmarlin/faq/questions/reorder/'.$recordId);
    }

**Comment by RedMarlin** [comment]
OK, fixed.

**Comment by kdoonboli** [comment]
Does it save on drag or is there a save button?
If it's auto save, then reordering doesn't seem to work for me. I can reorder, but the changes are not saved.

**Comment by RedMarlin** [comment]
Yes, it saves on drag and drop, there is no save button.
Did you upgrade using builtin October plugin update?
If the changes are not saved then check if in the table redmarlin_faq_questions there is a sort_order column. If not then something went wrong with the update.

**Comment by kdoonboli** [comment]
Yes, I upgraded using October update.
I think the problem was for existing rows -  the value for the order column defaults to zero after you added the new column the alter script. It would've been good to include a script with the update which would update the order column of existing rows and set them to the id.
I've already fixed it on my server myself, but others might get that issue.

I tried the reordering and noticed the order column gets updated! That's good! But when rendering the page, it doesn't seem to sort based on the order column! Nothing changes.

**Comment by RedMarlin** [comment]
To have manual sorting in frontend you need to use FaqList and set SortOrder property to "user order" as the default order (for sake of backward compatibility) is "Newest first"

**Comment by kdoonboli** [comment]
uhuh! Awesome! Looks like I've got it to work! Works flawlessly now :+1: 
Thanks for all the help!

**Comment by RedMarlin** [comment]
Thanks for the feedback. I have corrected all the issues and added Upgrade instructions on OctoberCMS marketplace.
