### ISSUE TITLE
Multiple categories 

### ISSUE THREAD

**Issue by mozeum** [RedMarlin/OctoberCMS-Faq#11]
Hey, can you display multiple categories on one page?

**Comment by RedMarlin** [comment]
Do you want to display list of categories or items(Q&A) from multiple categories?

**Comment by emryswizz** [comment]
Hello, yes if want to display from all categories...what we do?
Thank you.

**Comment by RedMarlin** [comment]
Sorry for the delay.
I will add component for that in the next version.

**Comment by RedMarlin** [comment]
Added new component in v 1.0.8 called FaqAll, it will display Q/A from all categories.
