### ISSUE TITLE
Can't edit categories using RainLab.Translate

### ISSUE THREAD

**Issue by alvaro-canepa** [RedMarlin/OctoberCMS-Faq#12]
When try to update a category, get the message `The lang must be a string`. 
This issue is only for update categories, create works fine.

![image](https://user-images.githubusercontent.com/5142298/34820254-c780bc0e-f69e-11e7-80ac-a87691e61991.png)

**Comment by RedMarlin** [comment]
What version of OctoberCMS are you using?
Can you show what kind of category name you are trying to save?

**Comment by alvaro-canepa** [comment]
Thanks for your quick response.
 
OC build **#431**
#### Category name
```
es: Información de envío
en: Shipping Information
```

**Comment by RedMarlin** [comment]
OK. I will test it today with #431 build and see what is happening there.

**Comment by RedMarlin** [comment]
OK. I have found the problem. 
I will fix it today and post updated version of the plugin alongside with other fixes.

**Comment by alvaro-canepa** [comment]
Thanks !!!

**Comment by RedMarlin** [comment]
The plugin is updated. Should take few more hours for v1.0.9 to show on OC marketplace.
