### ISSUE TITLE
Cannot notify the answer

### ISSUE THREAD

**Issue by opunbuds** [RedMarlin/OctoberCMS-Faq#2]
"No hint path defined for [faq]." on line 112 of C:\xampp\htdocs\moderat\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php

when im trying click notify button, i dont if im messup my env but im trying to clear my cache with php artisan config:cache its not work

thx

**Comment by RedMarlin** [comment]
Could you tell me what version of OctoberCMS and Faq plugin you are using?
Did you configured correctly email settings in System->Mail?

**Comment by RedMarlin** [comment]
OK, never mind, found it.
Thanks for noticing this bug. 
It is fixed now. You should just update the plugin directly from your October instance (The new version is 1.0.3)
