### ISSUE TITLE
Error after updated OctoberCMS stable release

### ISSUE THREAD

**Issue by vdomah** [RedMarlin/OctoberCMS-Faq#4]
Hello!

Got this error after update:

The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 6 (near "form: @/plugins/redmarlin/faq/models/question/fields.yaml").

**Comment by vdomah** [comment]
Need to replace @ by ~

**Comment by RedMarlin** [comment]
Thanks a lot. 
Fixed this and submitted new version to marketplace.
