### ISSUE TITLE
List categories+questions on a single page

### ISSUE THREAD

**Issue by jjwesd** [RedMarlin/OctoberCMS-Faq#5]
Hi,
your plugin looks very nice. Now I would like to list all the categories and questions on a single page is there an option for that?

 Cheers

**Comment by RedMarlin** [comment]
Sorry for late answer! I was out of office for a while.

There is no option specifically for that but you could use FaqLast component and set the number of questions to 999 or something like this and you will get a list of all questions sorted by date.

Alternatively you could write your own component for this plugin quite easily to show all the questions.

Hope this helps and sorry again for late answer.

**Comment by jjwesd** [comment]
Yes thanks for your answer, I did that indeed
